# Generated by Django 5.0.3 on 2024-03-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('best_pa', models.IntegerField(default=0)),
                ('test', models.IntegerField(default=0)),
            ],
        ),
    ]
